const PDFDocument = require("pdfkit");

function money(value) {
  return `£${Number(value || 0).toFixed(2)}`;
}

function generateInvoicePdf({ invoice, items, company }) {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50
  });

  doc.fontSize(22).text(company.name || "SVG Accounts", { align: "left" });
  doc.moveDown(0.3);

  doc.fontSize(10).fillColor("#555");
  if (company.address_line_1) doc.text(company.address_line_1);
  if (company.address_line_2) doc.text(company.address_line_2);
  if (company.city || company.postcode) {
    doc.text(`${company.city || ""} ${company.postcode || ""}`.trim());
  }
  if (company.country) doc.text(company.country);
  if (company.company_number) doc.text(`Company No: ${company.company_number}`);
  if (company.vat_number) doc.text(`VAT No: ${company.vat_number}`);

  doc.fillColor("#000");
  doc.moveDown(2);

  doc.fontSize(26).text("INVOICE", { align: "right" });
  doc.fontSize(12).text(invoice.invoice_number, { align: "right" });
  doc.moveDown();

  doc.fontSize(11);
  doc.text(`Issue date: ${invoice.issue_date}`, { align: "right" });
  doc.text(`Due date: ${invoice.due_date || "-"}`, { align: "right" });
  doc.text(`Status: ${invoice.status}`, { align: "right" });

  doc.moveDown(2);

  doc.fontSize(14).text("Bill To", { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(12).text(invoice.customer_name || "-");
  if (invoice.customer_email) doc.text(invoice.customer_email);
  if (invoice.customer_address) doc.text(invoice.customer_address);

  doc.moveDown(2);

  const tableTop = doc.y;
  const descX = 50;
  const qtyX = 300;
  const priceX = 355;
  const vatX = 430;
  const totalX = 500;

  doc.fontSize(10).fillColor("#555");
  doc.text("Description", descX, tableTop);
  doc.text("Qty", qtyX, tableTop);
  doc.text("Unit", priceX, tableTop);
  doc.text("VAT", vatX, tableTop);
  doc.text("Total", totalX, tableTop);

  doc.moveTo(50, tableTop + 16).lineTo(545, tableTop + 16).stroke();

  let y = tableTop + 28;

  doc.fillColor("#000");

  items.forEach((item) => {
    doc.fontSize(10);
    doc.text(item.description, descX, y, { width: 230 });
    doc.text(String(item.quantity), qtyX, y);
    doc.text(money(item.unit_price), priceX, y);
    doc.text(money(item.line_vat), vatX, y);
    doc.text(money(item.line_total), totalX, y);

    y += 28;
  });

  doc.moveTo(50, y).lineTo(545, y).stroke();
  y += 20;

  doc.fontSize(12);
  doc.text(`Subtotal: ${money(invoice.subtotal)}`, 390, y, { align: "right" });
  y += 20;
  doc.text(`VAT: ${money(invoice.vat_total)}`, 390, y, { align: "right" });
  y += 24;
  doc.fontSize(16).text(`Total: ${money(invoice.total)}`, 390, y, { align: "right" });

  if (invoice.notes) {
    doc.moveDown(3);
    doc.fontSize(12).text("Notes", { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(10).text(invoice.notes);
  }

  doc.moveDown(4);
  doc.fontSize(9).fillColor("#777").text("Generated by SVG Accounts private offline accounting software.", {
    align: "center"
  });

  return doc;
}

module.exports = generateInvoicePdf;
